export const Portfolios = [
  {
    purchase_id: 1,
    coin_token: 'ETH',
    unit: 0.27,
    total_cost: 780,
    percentage_to_sell_at: 25,
  },
  {
    purchase_id: 2,
    coin_token: 'GAS',
    unit: 30,
    total_cost: 455,
    percentage_to_sell_at: null,
  },
  {
    purchase_id: 3,
    coin_token: 'VET',
    unit: 500,
    total_cost: 45,
    percentage_to_sell_at: null,
  },
  {
    purchase_id: 4,
    coin_token: 'GAS',
    unit: 10,
    total_cost: 250,
    percentage_to_sell_at: 15,
  },
  {
    purchase_id: 5,
    coin_token: 'OXT',
    unit: 1000,
    total_cost: 1200,
    percentage_to_sell_at: null,
  },
  {
    purchase_id: 6,
    coin_token: 'ETH',
    unit: 0.5,
    total_cost: 1000,
    percentage_to_sell_at: null,
  },
  {
    purchase_id: 7,
    coin_token: 'BTC',
    unit: 1,
    total_cost: 13000,
    percentage_to_sell_at: 50,
  },
  {
    purchase_id: 8,
    coin_token: 'DOT',
    unit: 4,
    total_cost: 400,
    percentage_to_sell_at: 80,
  },
  {
    purchase_id: 9,
    coin_token: 'ADA',
    unit: 500,
    total_cost: 800,
    percentage_to_sell_at: null,
  },
  {
    purchase_id: 10,
    coin_token: 'UNI',
    unit: 2,
    total_cost: 30,
    percentage_to_sell_at: 10,
  },
  {
    purchase_id: 11,
    coin_token: 'FIL',
    unit: 1,
    total_cost: 250,
    percentage_to_sell_at: 80,
  },
];
